nav:
  - Home: index.md
  - Getting Started:
      - getting_started/index.md
      - Installation Options: getting_started/installation.md
      - Provider Setup: getting_started/providers.md
  - User Guide:
      - user_guide/index.md
      - CLI Reference: user_guide/cli.md
      - Profiles: user_guide/profiles.md
      - Agents: user_guide/agents.md
      - Sessions: user_guide/sessions.md
      - Collections: user_guide/collections.md
  - Developer Guides:
      - Foundation:
          - developer_guides/foundation/index.md
          - amplifier-foundation Library:
              - developer_guides/foundation/amplifier_foundation/index.md
              - Getting Started: developer_guides/foundation/amplifier_foundation/getting_started.md
              - Core Concepts: developer_guides/foundation/amplifier_foundation/concepts.md
              - Bundle System: developer_guides/foundation/amplifier_foundation/bundle_system.md
              - Utilities: developer_guides/foundation/amplifier_foundation/utilities.md
              - Patterns: developer_guides/foundation/amplifier_foundation/patterns.md
              - Examples:
                  - developer_guides/foundation/amplifier_foundation/examples/index.md
                  - Hello World: developer_guides/foundation/amplifier_foundation/examples/hello_world.md
                  - Custom Configuration: developer_guides/foundation/amplifier_foundation/examples/custom_configuration.md
                  - Custom Tool: developer_guides/foundation/amplifier_foundation/examples/custom_tool.md
                  - CLI Application: developer_guides/foundation/amplifier_foundation/examples/cli_application.md
                  - Multi-Agent System: developer_guides/foundation/amplifier_foundation/examples/multi_agent_system.md
              - API Reference: developer_guides/foundation/amplifier_foundation/api_reference.md
      - Applications:
          - developer_guides/applications/index.md
          - CLI Case Study: developer_guides/applications/cli_case_study.md
      - Modules:
          - developer/index.md
          - Module Development: developer/module_development.md
          - Contracts:
              - developer/contracts/index.md
              - Provider Contract: developer/contracts/provider.md
              - Tool Contract: developer/contracts/tool.md
              - Hook Contract: developer/contracts/hook.md
              - Orchestrator Contract: developer/contracts/orchestrator.md
              - Context Contract: developer/contracts/context.md
  - Architecture:
      - architecture/index.md
      - Overview: architecture/overview.md
      - Kernel Philosophy: architecture/kernel.md
      - Module System: architecture/modules.md
      - Mount Plans: architecture/mount_plans.md
      - Event System: architecture/events.md
  - Ecosystem:
      - ecosystem/index.md
      - Modules:
          - modules/index.md
          - Providers:
              - modules/providers/index.md
              - Anthropic: modules/providers/anthropic.md
              - OpenAI: modules/providers/openai.md
              - Azure OpenAI: modules/providers/azure.md
              - Ollama: modules/providers/ollama.md
              - vLLM: modules/providers/vllm.md
              - Mock: modules/providers/mock.md
          - Tools:
              - modules/tools/index.md
              - Filesystem: modules/tools/filesystem.md
              - Bash: modules/tools/bash.md
              - Web: modules/tools/web.md
              - Search: modules/tools/search.md
              - Task: modules/tools/task.md
              - Todo: modules/tools/todo.md
          - Orchestrators:
              - modules/orchestrators/index.md
              - Basic: modules/orchestrators/loop_basic.md
              - Streaming: modules/orchestrators/loop_streaming.md
              - Events: modules/orchestrators/loop_events.md
          - Contexts:
              - modules/contexts/index.md
              - Simple: modules/contexts/simple.md
              - Persistent: modules/contexts/persistent.md
          - Hooks:
              - modules/hooks/index.md
              - Logging: modules/hooks/logging.md
              - Approval: modules/hooks/approval.md
              - Redaction: modules/hooks/redaction.md
              - Backup: modules/hooks/backup.md
              - Cost-Aware Scheduler: modules/hooks/scheduler_cost_aware.md
              - Heuristic Scheduler: modules/hooks/scheduler_heuristic.md
              - Status Context: modules/hooks/status_context.md
              - Streaming UI: modules/hooks/streaming_ui.md
              - Todo Reminder: modules/hooks/todo_reminder.md
      - Libraries:
          - libraries/index.md
          - Profiles: libraries/profiles.md
          - Collections: libraries/collections.md
          - Config: libraries/config.md
          - Module Resolution: libraries/module_resolution.md
  - API Reference:
      - api/index.md
      - Core:
          - api/core/index.md
          - Session: api/core/session.md
          - Coordinator: api/core/coordinator.md
          - Hooks: api/core/hooks.md
          - Models: api/core/models.md
          - Events: api/core/events.md
      - CLI:
          - api/cli/index.md
  - Showcase:
      - showcase/index.md
  - Community:
      - community/index.md
      - Contributing: community/contributing.md
      - Roadmap: community/roadmap.md
